#!/bin/bash

gnome-terminal --tab --title="run_2_0" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_2_0 --P_IDX -2; exec bash'
gnome-terminal --tab --title="run_2_1" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_2_1 --P_IDX -2; exec bash'
gnome-terminal --tab --title="run_2_2" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_2_2 --P_IDX -2; exec bash'
gnome-terminal --tab --title="run_2_3" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_2_3 --P_IDX -2; exec bash'
gnome-terminal --tab --title="run_3_0" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_3_0 --P_IDX -3; exec bash'
gnome-terminal --tab --title="run_3_1" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_3_1 --P_IDX -3; exec bash'
gnome-terminal --tab --title="run_3_2" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_3_2 --P_IDX -3; exec bash'
gnome-terminal --tab --title="run_3_3" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_3_3 --P_IDX -3; exec bash'
gnome-terminal --tab --title="run_4_0" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_4_0 --P_IDX -4; exec bash'
gnome-terminal --tab --title="run_4_1" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_4_1 --P_IDX -4; exec bash'
gnome-terminal --tab --title="run_4_2" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_4_2 --P_IDX -4; exec bash'
gnome-terminal --tab --title="run_4_3" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_4_3 --P_IDX -4; exec bash'
gnome-terminal --tab --title="run_5_0" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_5_0 --P_IDX -5; exec bash'
gnome-terminal --tab --title="run_5_1" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_5_1 --P_IDX -5; exec bash'
gnome-terminal --tab --title="run_5_2" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_5_2 --P_IDX -5; exec bash'
gnome-terminal --tab --title="run_5_3" -- bash -c 'uv run python -O SA_ptp.py --run-dir run_5_3 --P_IDX -5; exec bash'