#!/usr/bin/env python3
"""
CP-SAT reconstruction of a permutation pi such that

    PivotProfile( pi(G_b) G_p ) = p_star,

with the convention pi(G_b) = G_b[:, pi], all arithmetic over F_2.

v2 changes relative to the butterfly version
--------------------------------------------

(1) MATROID-DUALITY REDUCTION (--dualize auto|always|never)

    Let H_b generate C_b^perp (an (n-k) x n full-row-rank matrix with
    G_b H_b^T = 0).  For standard polar G_p = F^{tensor m} one has
    F^{-1} = F and (F^{tensor m})^T = J F^{tensor m} J, where J is the
    index-reversal permutation a -> n-1-a.  A short computation gives:

        the dual code of  rowspace(pi(G_b) F)  is generated by
        pi(H_b) F^T = pi(H_b) J F J.

    The column matroid of a generator matrix and of a parity-check
    matrix of the same code are dual matroids.  The pivot profile is
    the min-weight (lex-min, left-to-right greedy) basis of the column
    matroid; by matroid duality its COMPLEMENT is the max-weight
    (right-to-left greedy) basis of the dual matroid.  Reading the dual
    generator with reversed columns turns right-to-left greedy back
    into an ordinary pivot profile, and the outer J cancels:

        PivotProfile( pi(G_b) F ) = p_star
            <=>
        PivotProfile( sigma(H_b) F ) = q_star,

    where sigma = pi o J  (as lists: sigma = pi[::-1]) and

        q_star = sorted{ n-1-j : j in {0..n-1} \\ p_star }.

    The dual instance has the SAME shape (some H_b, same F, some target
    profile) with k' = n-k rows.  When k > n/2 this shrinks every
    k-scaling quantity; the certificate layer scales as k^3, so e.g.
    (n,k)=(128,106) drops by (106/22)^3.  For (64,36) -> (64,28) the
    gain is more modest but free.

(2) PIVOT-ONLY CERTIFICATE (--certificate pivot-only|full)

    The old model constrained M = U W at every identity entry AND every
    pre-pivot zero entry M[i,j]=0, j<p_i (2014 entries at (64,36)),
    with z-products u_{i,r} AND w_{r,j} over ALL constrained columns:
    k^2 * O(n) products.

    Observation: the following two families are EQUIVALENT to the full
    profile condition, so the pre-pivot zeros can be dropped entirely:

        (a) U W[:, p_star] = I_k
            (certifies the k pivot columns are jointly independent;
             note U is then forced to equal W[:,p_star]^{-1}, so this
             adds no solution symmetry), and

        (b) for every non-pivot column j < p_star[-1]:
                W[:, j] in span{ W[:, p_l] : p_l < j }
            (the former "span rank cuts", now load-bearing; the case
             of zero previous pivots gives W[:,j] = 0 for j < p_0).

    Proof sketch: given (a)+(b), the rank of the column prefix [0..j]
    equals #{l : p_l <= j} for every j (non-pivots <= j lie in the span
    of pivots <= j, which are independent), so the rank jumps exactly
    at p_star; after p_star[-1] the rank is already k, so no further
    jumps are possible.  Conversely any W with profile p_star admits
    U = W[:,p_star]^{-1} and the (unique) span coefficients lambda.

    The z-layer therefore shrinks from k^2 * O(n) to k^3 products and
    the arity-k XOR family from ~#fixed_entries to k^2.

Additionally:

    - redundant LP-visible row-weight constraints
          sum_a b[r,a] = wt(G_b[r,:])
      (permutation invariance of row weight), and
    - decision strategy on pi ordered by DESCENDING POPCOUNT of the
      position index a: since F^{tensor m}[a,j]=1 iff supp(j) subseteq
      supp(a), late/high-popcount output columns depend on few
      positions (column n-1 depends on position n-1 alone), so fixing
      high-popcount positions first fails fast on the sparsest
      constraints.

Usage:

    python cpsat_pivot_reconstruct_v2.py                # self-tests
    python cpsat_pivot_reconstruct_v2.py data.npz --time 14400 --workers 12

Options:

    --dualize {auto,always,never}      auto: dualize iff k > n/2 and Gp
                                       is standard polar (default)
    --certificate {pivot-only,full}    default pivot-only
    --w-encoding {auto,butterfly,dense}
    --rank-cuts {none,prefix-zero,span}   only meaningful with
                                          --certificate full (pivot-only
                                          always uses span; it is part
                                          of the model there)
    --branch {popcount,first}          pi branching order
"""

from __future__ import annotations

import argparse
import math
import sys
from typing import Dict, List, Optional, Tuple

import numpy as np
from ortools.sat.python import cp_model


# ============================================================
# Basic F_2 utilities
# ============================================================

def gf2(A: np.ndarray) -> np.ndarray:
    return (np.asarray(A, dtype=np.uint8) & 1)


def gf2_matmul(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    A = gf2(A)
    B = gf2(B)
    return ((A.astype(np.uint32) @ B.astype(np.uint32)) & 1).astype(np.uint8)


def gf2_rank(A: np.ndarray) -> int:
    A = gf2(A).copy()
    m, n = A.shape
    rank = 0
    for col in range(n):
        pivot = None
        for row in range(rank, m):
            if A[row, col]:
                pivot = row
                break
        if pivot is None:
            continue
        if pivot != rank:
            A[[rank, pivot]] = A[[pivot, rank]]
        for row in range(m):
            if row != rank and A[row, col]:
                A[row, :] ^= A[rank, :]
        rank += 1
        if rank == m:
            break
    return rank


def gf2_rref(A: np.ndarray) -> Tuple[np.ndarray, List[int]]:
    """
    Reduced row echelon form over F_2.  Returns (R, pivot_columns).
    """
    R = gf2(A).copy()
    m, n = R.shape
    pivots: List[int] = []
    row = 0
    for col in range(n):
        piv = None
        for r in range(row, m):
            if R[r, col]:
                piv = r
                break
        if piv is None:
            continue
        if piv != row:
            R[[row, piv]] = R[[piv, row]]
        for r in range(m):
            if r != row and R[r, col]:
                R[r, :] ^= R[row, :]
        pivots.append(col)
        row += 1
        if row == m:
            break
    return R, pivots


def gf2_nullspace(A: np.ndarray) -> np.ndarray:
    """
    Basis of the right nullspace of A over F_2, returned as rows of H,
    so that A H^T = 0 and H has full row rank n - rank(A).
    """
    A = gf2(A)
    m, n = A.shape
    R, pivots = gf2_rref(A)
    pivot_set = set(pivots)
    free = [c for c in range(n) if c not in pivot_set]

    H = np.zeros((len(free), n), dtype=np.uint8)
    for i, f in enumerate(free):
        H[i, f] = 1
        for r, p in enumerate(pivots):
            H[i, p] = R[r, f]
    return H


def column_pivot_profile_gf2(A: np.ndarray) -> List[int]:
    """
    Column rank profile of A over F_2 (left-to-right greedy).
    """
    A = gf2(A)
    k, n = A.shape
    basis = [0 for _ in range(k)]
    pivots: List[int] = []

    for j in range(n):
        v = 0
        for r in range(k):
            if A[r, j]:
                v |= (1 << r)
        for p in reversed(range(k)):
            if ((v >> p) & 1) and basis[p] != 0:
                v ^= basis[p]
        if v != 0:
            p = v.bit_length() - 1
            basis[p] = v
            for q in range(k):
                if q != p and basis[q] != 0 and ((basis[q] >> p) & 1):
                    basis[q] ^= v
            pivots.append(j)
    return pivots


def polar_matrix(m: int) -> np.ndarray:
    F = np.array([[1, 0], [1, 1]], dtype=np.uint8)
    G = np.array([[1]], dtype=np.uint8)
    for _ in range(m):
        G = np.kron(G, F).astype(np.uint8) & 1
    return G


def is_power_of_two(n: int) -> bool:
    return n > 0 and (n & (n - 1)) == 0


def polar_log2_size(n: int) -> int:
    if not is_power_of_two(n):
        raise ValueError(f"n must be a power of two for polar butterfly, got n={n}.")
    return int(math.log2(n))


def is_standard_polar_matrix(Gp: np.ndarray) -> bool:
    Gp = gf2(Gp)
    if Gp.ndim != 2 or Gp.shape[0] != Gp.shape[1]:
        return False
    n = Gp.shape[0]
    if not is_power_of_two(n):
        return False
    return np.array_equal(Gp, polar_matrix(polar_log2_size(n)))


def random_full_row_rank_binary_matrix(k: int, n: int, rng: np.random.Generator) -> np.ndarray:
    while True:
        Gb = rng.integers(0, 2, size=(k, n), dtype=np.uint8)
        if gf2_rank(Gb) == k:
            return Gb


def popcount_descending_order(n: int) -> List[int]:
    return sorted(range(n), key=lambda a: (-bin(a).count("1"), a))


# ============================================================
# Matroid-duality reduction
# ============================================================

def dual_target_profile(n: int, p_star: List[int]) -> List[int]:
    """
    q_star = sorted{ n-1-j : j not in p_star }.
    """
    pset = set(p_star)
    return sorted(n - 1 - j for j in range(n) if j not in pset)


def dualize_instance(Gb: np.ndarray, p_star: List[int]) -> Tuple[np.ndarray, List[int]]:
    """
    Given a primal instance (Gb, F^{tensor m}, p_star), return the dual
    instance (Hb, q_star) such that

        PivotProfile(pi(Gb) F) = p_star
            <=>
        PivotProfile(sigma(Hb) F) = q_star,   sigma = pi[::-1].

    Requires Gp to be the standard polar matrix (this is checked by the
    caller); the identity (F^{tensor m})^T = J F^{tensor m} J with
    J: a -> n-1-a is what makes the dual instance have the same form.
    """
    Gb = gf2(Gb)
    k, n = Gb.shape
    Hb = gf2_nullspace(Gb)
    if Hb.shape != (n - k, n):
        raise RuntimeError("Nullspace has unexpected shape; Gb must have full row rank.")
    q_star = dual_target_profile(n, p_star)
    if len(q_star) != n - k:
        raise RuntimeError("Dual target profile has wrong length.")
    return Hb, q_star


def primal_pi_from_dual_sigma(sigma: List[int]) -> List[int]:
    """
    pi(a) = sigma(n-1-a), i.e. pi = sigma reversed as a list.
    (J is an involution, so the same map inverts itself.)
    """
    return list(reversed(sigma))


# ============================================================
# CP-SAT helpers
# ============================================================

def add_xor_eq(
    model: cp_model.CpModel,
    lits: List[cp_model.IntVar],
    rhs: int,
    true_lit: cp_model.IntVar,
) -> None:
    """
    Enforce XOR(lits) == rhs over F_2.
    """
    rhs = int(rhs) & 1
    lits = list(lits)
    if len(lits) == 0:
        if rhs == 0:
            return
        model.Add(true_lit == 0)
        return
    if rhs == 1:
        model.AddBoolXOr(lits)
    else:
        model.AddBoolXOr(lits + [true_lit])


def add_and_eq(
    model: cp_model.CpModel,
    z: cp_model.IntVar,
    x: cp_model.IntVar,
    y: cp_model.IntVar,
) -> None:
    model.Add(z <= x)
    model.Add(z <= y)
    model.Add(z >= x + y - 1)


# ============================================================
# W encodings
# ============================================================

def build_w_dense(
    model: cp_model.CpModel,
    b: Dict[Tuple[int, int], cp_model.IntVar],
    Gp: np.ndarray,
    k: int,
    n: int,
    constrained_cols: List[int],
    true_lit: cp_model.IntVar,
) -> Tuple[Dict[Tuple[int, int], cp_model.IntVar], Dict[str, int]]:
    w: Dict[Tuple[int, int], cp_model.IntVar] = {}
    num_w_vars = 0
    num_w_xor_constraints = 0
    total_support = 0

    for r in range(k):
        for j in constrained_cols:
            w[r, j] = model.NewBoolVar(f"w[{r},{j}]")
            num_w_vars += 1
            support = [a for a in range(n) if int(Gp[a, j]) == 1]
            total_support += len(support)
            terms = [b[r, a] for a in support]
            add_xor_eq(model, terms + [w[r, j]], 0, true_lit)
            num_w_xor_constraints += 1

    stats = {
        "w_vars": num_w_vars,
        "w_xor_constraints": num_w_xor_constraints,
        "w_total_support": total_support,
        "butterfly_x_vars": 0,
        "butterfly_xor_constraints": 0,
    }
    return w, stats


def build_w_polar_butterfly(
    model: cp_model.CpModel,
    b: Dict[Tuple[int, int], cp_model.IntVar],
    k: int,
    n: int,
    constrained_cols: List[int],
    true_lit: cp_model.IntVar,
) -> Tuple[Dict[Tuple[int, int], cp_model.IntVar], Dict[str, int]]:
    """
    Polar butterfly encoding of W = pi(Gb) F^{tensor m}.
    """
    m = polar_log2_size(n)

    x_prev: Dict[Tuple[int, int], cp_model.IntVar] = {
        (r, a): b[r, a] for r in range(k) for a in range(n)
    }

    num_x_vars = 0
    num_xor_constraints = 0

    for t in range(m):
        s = 1 << t
        x_next: Dict[Tuple[int, int], cp_model.IntVar] = {}
        for r in range(k):
            for a in range(n):
                if (a & s) == 0:
                    out = model.NewBoolVar(f"x[{t+1},{r},{a}]")
                    num_x_vars += 1
                    add_xor_eq(
                        model,
                        [out, x_prev[r, a], x_prev[r, a + s]],
                        0,
                        true_lit,
                    )
                    num_xor_constraints += 1
                    x_next[r, a] = out
                else:
                    x_next[r, a] = x_prev[r, a]
        x_prev = x_next

    # x_prev is now the final layer x^{(m)}; alias W columns (outside t-loop).
    w: Dict[Tuple[int, int], cp_model.IntVar] = {}
    for r in range(k):
        for j in constrained_cols:
            w[r, j] = x_prev[r, j]

    stats = {
        "w_vars": 0,
        "w_xor_constraints": 0,
        "w_total_support": 0,
        "butterfly_x_vars": num_x_vars,
        "butterfly_xor_constraints": num_xor_constraints,
    }
    return w, stats


# ============================================================
# Span-membership constraints (load-bearing in pivot-only mode)
# ============================================================

def add_span_membership_constraints(
    model: cp_model.CpModel,
    w: Dict[Tuple[int, int], cp_model.IntVar],
    k: int,
    p_star: List[int],
    constrained_cols: List[int],
    true_lit: cp_model.IntVar,
    mode: str = "span",
) -> Dict[str, int]:
    """
    For every non-pivot constrained column j <= p_star[-1]:

        W[:, j] = XOR_{l : p_l < j} lambda[l,j] W[:, p_l],

    encoded entrywise via y[l,r,j] = lambda[l,j] AND W[r,p_l] and
    W[r,j] = XOR_l y[l,r,j].  The q(j)=0 case gives W[:,j] = 0.

    In certificate='pivot-only' this family is part of the model
    (together with U W[:,p_star] = I_k it is equivalent to the full
    pivot-profile condition).  In certificate='full' it is a redundant
    strengthening, exactly as in v1.
    """
    mode = str(mode).lower()
    if mode not in {"none", "prefix-zero", "span"}:
        raise ValueError("mode must be one of: none, prefix-zero, span.")

    stats = {
        "span_mode": mode,
        "span_zero_constraints": 0,
        "span_lambda_vars": 0,
        "span_and_vars": 0,
        "span_and_constraints": 0,
        "span_xor_constraints": 0,
        "span_columns": 0,
    }

    if mode == "none":
        return stats

    p_star = [int(x) for x in p_star]
    pivot_set = set(p_star)
    constrained_set = set(constrained_cols)

    if mode == "prefix-zero":
        for j in range(p_star[0]):
            if j not in constrained_set:
                raise ValueError(f"prefix-zero column j={j} not in constrained_cols.")
            stats["span_columns"] += 1
            for r in range(k):
                model.Add(w[r, j] == 0)
                stats["span_zero_constraints"] += 1
        return stats

    for j in constrained_cols:
        j = int(j)
        if j in pivot_set:
            continue
        if j > p_star[-1]:
            continue

        prev_pivots = [p for p in p_star if p < j]
        q = len(prev_pivots)
        stats["span_columns"] += 1

        if q == 0:
            for r in range(k):
                model.Add(w[r, j] == 0)
                stats["span_zero_constraints"] += 1
            continue

        lambdas = [model.NewBoolVar(f"lam[{ell},{j}]") for ell in range(q)]
        stats["span_lambda_vars"] += q

        for r in range(k):
            terms = []
            for ell, p in enumerate(prev_pivots):
                y = model.NewBoolVar(f"y[{ell},{r},{j}]")
                add_and_eq(model, y, lambdas[ell], w[r, p])
                stats["span_and_vars"] += 1
                stats["span_and_constraints"] += 1
                terms.append(y)
            add_xor_eq(model, terms + [w[r, j]], 0, true_lit)
            stats["span_xor_constraints"] += 1

    return stats


# ============================================================
# CP-SAT model
# ============================================================

def build_pivot_reconstruction_model(
    Gb: np.ndarray,
    Gp: np.ndarray,
    p_star: List[int],
    *,
    w_encoding: str = "auto",
    certificate: str = "pivot-only",
    rank_cuts: str = "span",
    row_weight_cuts: bool = True,
    branch: str = "popcount",
    verbose: bool = True,
):
    """
    Build the CP-SAT feasibility model.

    certificate = 'pivot-only':
        - span-membership constraints for all non-pivot columns
          j <= p_star[-1]  (load-bearing),
        - z-products and identity XORs only over the k pivot columns:
              M[:, p_star] = U W[:, p_star] = I_k.
        No pre-pivot zero constraints on M are needed; the two families
        above are equivalent to the full pivot-profile condition.

    certificate = 'full':
        v1 behavior: M[:,p_star] = I_k, M[i,j] = 0 for j < p_i, with z
        over all constrained columns; rank_cuts as redundant cuts.
    """
    Gb = gf2(Gb)
    Gp = gf2(Gp)
    p_star = [int(x) for x in p_star]

    k, n = Gb.shape

    if Gp.shape != (n, n):
        raise ValueError(f"Gp must have shape ({n},{n}), got {Gp.shape}.")
    if len(p_star) != k:
        raise ValueError(f"p_star must have length k={k}, got {len(p_star)}.")
    if sorted(p_star) != p_star:
        raise ValueError("p_star must be sorted increasingly.")
    if len(set(p_star)) != len(p_star):
        raise ValueError("p_star must contain distinct entries.")
    if min(p_star) < 0 or max(p_star) >= n:
        raise ValueError("p_star entries must lie in {0,...,n-1}.")
    if gf2_rank(Gb) != k:
        raise ValueError("Gb must have full row rank k over F_2.")
    if gf2_rank(Gp) != n:
        raise ValueError("Gp must be invertible over F_2.")

    certificate = str(certificate).lower()
    if certificate not in {"pivot-only", "full"}:
        raise ValueError("certificate must be 'pivot-only' or 'full'.")

    w_encoding = str(w_encoding).lower()
    if w_encoding not in {"auto", "dense", "butterfly"}:
        raise ValueError("w_encoding must be one of: auto, dense, butterfly.")

    polar_ok = is_standard_polar_matrix(Gp)
    if w_encoding == "auto":
        actual_w_encoding = "butterfly" if polar_ok else "dense"
    elif w_encoding == "butterfly":
        if not polar_ok:
            raise ValueError("--w-encoding butterfly requires standard polar Gp.")
        actual_w_encoding = "butterfly"
    else:
        actual_w_encoding = "dense"

    model = cp_model.CpModel()

    true_lit = model.NewBoolVar("TRUE")
    model.Add(true_lit == 1)

    # --------------------------------------------------------
    # 1. Permutation variables
    # --------------------------------------------------------
    pi = [model.NewIntVar(0, n - 1, f"pi[{a}]") for a in range(n)]
    model.AddAllDifferent(pi)

    # --------------------------------------------------------
    # 2. U variables
    # --------------------------------------------------------
    u: Dict[Tuple[int, int], cp_model.IntVar] = {}
    for i in range(k):
        for r in range(k):
            u[i, r] = model.NewBoolVar(f"u[{i},{r}]")

    # --------------------------------------------------------
    # 3. Constrained M entries / columns
    # --------------------------------------------------------
    fixed_m: Dict[Tuple[int, int], int] = {}

    def fix_m(i: int, j: int, rhs: int) -> None:
        rhs = int(rhs) & 1
        key = (i, j)
        if key in fixed_m and fixed_m[key] != rhs:
            raise ValueError(f"Contradictory constraints on m[{i},{j}].")
        fixed_m[key] = rhs

    if certificate == "full":
        for i in range(k):
            for ell, p in enumerate(p_star):
                fix_m(i, p, 1 if i == ell else 0)
        for i in range(k):
            for j in range(p_star[i]):
                fix_m(i, j, 0)
        constrained_cols = sorted({j for (_, j) in fixed_m.keys()})
        z_cols = constrained_cols
        span_mode = rank_cuts
    else:
        # pivot-only: identity entries only, on pivot columns.
        for i in range(k):
            for ell, p in enumerate(p_star):
                fix_m(i, p, 1 if i == ell else 0)
        # W is needed at every column up to the last pivot (pivots for
        # the certificate, non-pivots for the span constraints).
        constrained_cols = list(range(p_star[-1] + 1))
        z_cols = list(p_star)
        span_mode = "span"

    # --------------------------------------------------------
    # 4. b_{r,a} = G_b[r, pi_a]
    # --------------------------------------------------------
    b: Dict[Tuple[int, int], cp_model.IntVar] = {}
    for r in range(k):
        row_values = [int(Gb[r, t]) for t in range(n)]
        row_all_zero = all(v == 0 for v in row_values)
        row_all_one = all(v == 1 for v in row_values)
        for a in range(n):
            b[r, a] = model.NewBoolVar(f"b[{r},{a}]")
            if row_all_zero:
                model.Add(b[r, a] == 0)
            elif row_all_one:
                model.Add(b[r, a] == 1)
            else:
                model.AddElement(pi[a], row_values, b[r, a])

    # --------------------------------------------------------
    # 4b. Redundant LP-visible row-weight constraints:
    #     sum_a b[r,a] = wt(Gb[r,:])  (permutation preserves weight).
    # --------------------------------------------------------
    num_row_weight_cuts = 0
    if row_weight_cuts:
        for r in range(k):
            wt = int(Gb[r, :].sum())
            model.Add(sum(b[r, a] for a in range(n)) == wt)
            num_row_weight_cuts += 1

    # --------------------------------------------------------
    # 5. W = pi(Gb) Gp on constrained columns
    # --------------------------------------------------------
    if actual_w_encoding == "butterfly":
        w, w_stats = build_w_polar_butterfly(
            model, b, k, n, constrained_cols, true_lit
        )
    else:
        w, w_stats = build_w_dense(
            model=model, b=b, Gp=Gp, k=k, n=n,
            constrained_cols=constrained_cols, true_lit=true_lit,
        )

    # --------------------------------------------------------
    # 5b. Span-membership constraints
    # --------------------------------------------------------
    span_stats = add_span_membership_constraints(
        model=model, w=w, k=k, p_star=p_star,
        constrained_cols=constrained_cols, true_lit=true_lit,
        mode=span_mode,
    )

    # --------------------------------------------------------
    # 6. Certificate products z_{i,r,j} = u_{i,r} AND w_{r,j},
    #    only over z_cols.
    # --------------------------------------------------------
    z: Dict[Tuple[int, int, int], cp_model.IntVar] = {}
    for i in range(k):
        for r in range(k):
            for j in z_cols:
                z[i, r, j] = model.NewBoolVar(f"z[{i},{r},{j}]")
                add_and_eq(model, z[i, r, j], u[i, r], w[r, j])

    # --------------------------------------------------------
    # 7. m_{i,j} = XOR_r z_{i,r,j} for the fixed entries.
    # --------------------------------------------------------
    for (i, j), rhs in fixed_m.items():
        terms = [z[i, r, j] for r in range(k)]
        add_xor_eq(model, terms, rhs, true_lit)

    # --------------------------------------------------------
    # 8. Decision strategy on pi.
    # --------------------------------------------------------
    if branch == "popcount":
        order = popcount_descending_order(n)
        pi_ordered = [pi[a] for a in order]
    else:
        pi_ordered = pi
    model.AddDecisionStrategy(
        pi_ordered, cp_model.CHOOSE_FIRST, cp_model.SELECT_MIN_VALUE
    )

    if verbose:
        print("CP-SAT model built.")
        print(f"  n = {n}")
        print(f"  k = {k}")
        print(f"  certificate = {certificate}")
        print(f"  |p_star| = {len(p_star)}")
        print(f"  constrained M entries = {len(fixed_m)}")
        print(f"  W columns materialized = {len(constrained_cols)}")
        print(f"  z columns (certificate) = {len(z_cols)}")
        print(f"  W encoding = {actual_w_encoding}")
        print(f"  permutation vars = {len(pi)} integer vars")
        print(f"  U vars = {k*k}")
        print(f"  b vars = {k*n}")
        print(f"  row-weight cuts = {num_row_weight_cuts}")
        if actual_w_encoding == "dense":
            print(f"  w vars = {w_stats['w_vars']}")
            print(f"  dense W XOR constraints = {w_stats['w_xor_constraints']}")
        else:
            print(f"  butterfly x vars = {w_stats['butterfly_x_vars']}")
            print(f"  butterfly XOR constraints = {w_stats['butterfly_xor_constraints']}")
        print(f"  span mode = {span_stats['span_mode']}")
        print(f"  span columns = {span_stats['span_columns']}")
        print(f"  span zero constraints = {span_stats['span_zero_constraints']}")
        print(f"  span lambda vars = {span_stats['span_lambda_vars']}")
        print(f"  span AND vars = {span_stats['span_and_vars']}")
        print(f"  span XOR constraints = {span_stats['span_xor_constraints']}")
        print(f"  z vars = {k*k*len(z_cols)}")
        print(f"  branch order = {branch}")

    variables = {
        "pi": pi,
        "u": u,
        "b": b,
        "w": w,
        "z": z,
        "fixed_m": fixed_m,
        "constrained_cols": constrained_cols,
        "z_cols": z_cols,
        "w_encoding": actual_w_encoding,
        "w_stats": w_stats,
        "span_stats": span_stats,
        "certificate": certificate,
    }
    return model, variables


# ============================================================
# Solver
# ============================================================

def _solve_single_instance(
    Gb: np.ndarray,
    Gp: np.ndarray,
    p_star: List[int],
    *,
    time_limit_sec: float,
    workers: int,
    log: bool,
    w_encoding: str,
    certificate: str,
    rank_cuts: str,
    row_weight_cuts: bool,
    branch: str,
    verbose: bool,
    hint_pi: Optional[List[int]] = None,
) -> Optional[Tuple[List[int], np.ndarray, str]]:
    model, variables = build_pivot_reconstruction_model(
        Gb, Gp, p_star,
        w_encoding=w_encoding,
        certificate=certificate,
        rank_cuts=rank_cuts,
        row_weight_cuts=row_weight_cuts,
        branch=branch,
        verbose=verbose,
    )

    pi_vars = variables["pi"]
    u_vars = variables["u"]
    k, n = gf2(Gb).shape

    if hint_pi is not None:
        for a in range(n):
            model.AddHint(pi_vars[a], int(hint_pi[a]))

    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = float(time_limit_sec)
    solver.parameters.num_search_workers = int(workers)
    solver.parameters.log_search_progress = bool(log)

    status = solver.Solve(model)
    status_name = solver.StatusName(status)
    print(f"Solver status: {status_name}")

    if status not in (cp_model.FEASIBLE, cp_model.OPTIMAL):
        return None

    pi_sol = [solver.Value(pi_vars[a]) for a in range(n)]
    U_sol = np.zeros((k, k), dtype=np.uint8)
    for i in range(k):
        for r in range(k):
            U_sol[i, r] = solver.Value(u_vars[i, r]) & 1

    return pi_sol, U_sol, status_name


def solve_reconstruction(
    Gb: np.ndarray,
    Gp: np.ndarray,
    p_star: List[int],
    *,
    time_limit_sec: float = 60.0,
    workers: int = 8,
    log: bool = False,
    w_encoding: str = "auto",
    certificate: str = "pivot-only",
    rank_cuts: str = "span",
    row_weight_cuts: bool = True,
    branch: str = "popcount",
    dualize: str = "auto",
    hint_pi: Optional[List[int]] = None,
    verbose: bool = True,
) -> Optional[Tuple[List[int], Optional[np.ndarray]]]:
    """
    Solve the reconstruction problem, possibly on the dual instance.

    Returns (pi, U) where U certifies the instance that was actually
    solved (U is None when the dual was solved, since the returned pi
    is for the primal; the profile itself is re-verified numerically).
    """
    Gb = gf2(Gb)
    Gp = gf2(Gp)
    p_star = [int(x) for x in p_star]
    k, n = Gb.shape

    dualize = str(dualize).lower()
    if dualize not in {"auto", "always", "never"}:
        raise ValueError("dualize must be one of: auto, always, never.")

    polar_ok = is_standard_polar_matrix(Gp)

    if dualize == "always" and not polar_ok:
        raise ValueError("--dualize always requires standard polar Gp.")

    use_dual = False
    if polar_ok and 0 < n - k < n:
        if dualize == "always":
            use_dual = True
        elif dualize == "auto":
            use_dual = (n - k) < k  # strictly smaller dual instance

    if not use_dual:
        if verbose:
            print(f"Solving PRIMAL instance: n={n}, k={k}.")
        result = _solve_single_instance(
            Gb, Gp, p_star,
            time_limit_sec=time_limit_sec, workers=workers, log=log,
            w_encoding=w_encoding, certificate=certificate,
            rank_cuts=rank_cuts, row_weight_cuts=row_weight_cuts,
            branch=branch, verbose=verbose, hint_pi=hint_pi,
        )
        if result is None:
            return None
        pi_sol, U_sol, _ = result
        return pi_sol, U_sol

    # ---------------- dual path ----------------
    Hb, q_star = dualize_instance(Gb, p_star)
    if verbose:
        print(f"Matroid-duality reduction: primal (n={n}, k={k}) "
              f"-> dual (n={n}, k'={n-k}).")
        print(f"  dual target q_star = {q_star}")

    hint_sigma = None
    if hint_pi is not None:
        hint_sigma = list(reversed([int(x) for x in hint_pi]))

    result = _solve_single_instance(
        Hb, Gp, q_star,
        time_limit_sec=time_limit_sec, workers=workers, log=log,
        w_encoding=w_encoding, certificate=certificate,
        rank_cuts=rank_cuts, row_weight_cuts=row_weight_cuts,
        branch=branch, verbose=verbose, hint_pi=hint_sigma,
    )
    if result is None:
        return None

    sigma_sol, U_dual, _ = result

    # Verify the dual solution against the dual instance (with its U).
    print()
    print("Verifying DUAL solution against dual instance:")
    ok_dual = verify_solution(Hb, Gp, q_star, sigma_sol, U_dual)
    if not ok_dual:
        print("WARNING: dual solution failed dual verification.")
        return None

    pi_sol = primal_pi_from_dual_sigma(sigma_sol)
    return pi_sol, None


# ============================================================
# Verification
# ============================================================

def verify_solution(
    Gb: np.ndarray,
    Gp: np.ndarray,
    p_star: List[int],
    pi_sol: List[int],
    U_sol: Optional[np.ndarray] = None,
    *,
    print_matrices: bool = False,
) -> bool:
    Gb = gf2(Gb)
    Gp = gf2(Gp)
    p_star = [int(x) for x in p_star]
    k, n = Gb.shape

    piGb = Gb[:, pi_sol]
    W = gf2_matmul(piGb, Gp)
    actual_pivots = column_pivot_profile_gf2(W)

    print("Target pivot profile: ", p_star)
    print("Actual pivot profile: ", actual_pivots)

    ok_profile = (actual_pivots == p_star)
    print("Pivot profile check:", "PASS" if ok_profile else "FAIL")

    ok_cert = True
    if U_sol is not None:
        U_sol = gf2(U_sol)
        M = gf2_matmul(U_sol, W)

        ok_identity = all(
            int(M[i, p]) == (1 if i == ell else 0)
            for i in range(k)
            for ell, p in enumerate(p_star)
        )
        print("U-certificate identity check:", "PASS" if ok_identity else "FAIL")
        ok_cert = ok_identity

        if print_matrices:
            print("pi(Gb) =\n", piGb)
            print("W =\n", W)
            print("U =\n", U_sol)
            print("M = U W =\n", M)

    return ok_profile and ok_cert


# ============================================================
# Self-tests
# ============================================================

def self_test_duality(trials: int = 40, seed: int = 1) -> None:
    """
    Numerical check of the matroid-duality identity:

        p_star = Profile(pi(Gb) F)
            =>
        Profile(sigma(Hb) F) = q_star,  sigma = pi[::-1],
        q_star = sorted{n-1-j : j not in p_star}.

    Also checks the inverse mapping pi = sigma[::-1].
    """
    rng = np.random.default_rng(seed)
    checked = 0
    for m in (3, 4, 5):
        n = 2 ** m
        F = polar_matrix(m)
        for _ in range(trials):
            k = int(rng.integers(1, n))
            Gb = random_full_row_rank_binary_matrix(k, n, rng)
            pi = list(rng.permutation(n))
            p = column_pivot_profile_gf2(gf2_matmul(Gb[:, pi], F))
            if len(p) != k:
                raise RuntimeError("full-rank Gb must yield k pivots")

            Hb, q = dualize_instance(Gb, p)
            sigma = list(reversed(pi))
            q_check = column_pivot_profile_gf2(gf2_matmul(Hb[:, sigma], F))
            if q_check != q:
                raise AssertionError(
                    f"DUALITY CHECK FAILED at n={n}, k={k}:\n"
                    f"  pi = {pi}\n  p* = {p}\n"
                    f"  expected q* = {q}\n  got        = {q_check}"
                )
            if primal_pi_from_dual_sigma(sigma) != pi:
                raise AssertionError("pi <-> sigma mapping is not involutive")
            checked += 1
    print(f"[self-test] duality identity verified on {checked} random instances "
          f"(n in {{8,16,32}}).  PASS")


def built_in_self_test() -> Tuple[np.ndarray, np.ndarray, List[int], List[int]]:
    """
    Reachable test instance with k > n/2 so that the dual path is
    exercised under --dualize auto.
    """
    rng = np.random.default_rng(0)
    m = 4
    n = 2 ** m
    k = 10

    Gp = polar_matrix(m)
    Gb = random_full_row_rank_binary_matrix(k, n, rng)
    true_pi = list(rng.permutation(n))

    W_true = gf2_matmul(Gb[:, true_pi], Gp)
    p_star = column_pivot_profile_gf2(W_true)
    if len(p_star) != k:
        raise RuntimeError("Unexpected pivot profile length in self-test.")

    print("Built-in self-test instance:")
    print(f"  n = {n}, k = {k}  (k > n/2, dual path active under auto)")
    print(f"  true pi = {true_pi}")
    print(f"  p_star from true pi = {p_star}")
    return Gb, Gp, p_star, true_pi


def load_npz_instance(path: str) -> Tuple[np.ndarray, np.ndarray, List[int]]:
    data = np.load(path, allow_pickle=False)
    if "Gb" not in data or "Gp" not in data or "p_star" not in data:
        raise ValueError("npz file must contain arrays Gb, Gp, and p_star.")
    Gb = gf2(data["Gb"])
    Gp = gf2(data["Gp"])
    p_star = [int(x) for x in np.asarray(data["p_star"]).reshape(-1)]
    return Gb, Gp, p_star


# ============================================================
# CLI
# ============================================================

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("npz", nargs="?", default=None,
                        help="Optional .npz file containing Gb, Gp, p_star.")
    parser.add_argument("--time", type=float, default=60.0,
                        help="CP-SAT time limit in seconds.")
    parser.add_argument("--workers", "--worker", type=int, default=8,
                        help="Number of CP-SAT search workers.")
    parser.add_argument("--log", action="store_true",
                        help="Enable CP-SAT search log.")
    parser.add_argument("--print-matrices", action="store_true",
                        help="Print pi(Gb), W, U, M after solving.")
    parser.add_argument("--w-encoding", choices=["auto", "butterfly", "dense"],
                        default="auto")
    parser.add_argument("--certificate", choices=["pivot-only", "full"],
                        default="pivot-only",
                        help="pivot-only: U-certificate on pivot columns + "
                             "span membership (equivalent, much smaller). "
                             "full: v1 model.")
    parser.add_argument("--rank-cuts", choices=["none", "prefix-zero", "span"],
                        default="span",
                        help="Only used with --certificate full.")
    parser.add_argument("--dualize", choices=["auto", "always", "never"],
                        default="auto",
                        help="Solve the (n-k)-row dual instance when smaller.")
    parser.add_argument("--branch", choices=["popcount", "first"],
                        default="popcount",
                        help="pi branching order (popcount: descending "
                             "popcount of position index).")
    parser.add_argument("--no-row-weight-cuts", action="store_true",
                        help="Disable redundant row-weight constraints.")
    parser.add_argument("--skip-duality-selftest", action="store_true",
                        help="Skip the numeric duality self-test.")
    args = parser.parse_args()

    if not args.skip_duality_selftest:
        self_test_duality()
        print()

    if args.npz is None:
        Gb, Gp, p_star, true_pi = built_in_self_test()
    else:
        Gb, Gp, p_star = load_npz_instance(args.npz)
        true_pi = None

    print()
    print("Solving reconstruction problem...")
    result = solve_reconstruction(
        Gb, Gp, p_star,
        time_limit_sec=args.time,
        workers=args.workers,
        log=args.log,
        w_encoding=args.w_encoding,
        certificate=args.certificate,
        rank_cuts=args.rank_cuts,
        row_weight_cuts=not args.no_row_weight_cuts,
        branch=args.branch,
        dualize=args.dualize,
        verbose=True,
    )

    if result is None:
        return 1

    pi_sol, U_sol = result

    print()
    print("Recovered pi:")
    print(pi_sol)

    if true_pi is not None:
        print()
        print("Original true pi used to generate p_star:")
        print(true_pi)
        print("Note: recovered pi need not equal true pi; many pi share "
              "the same pivot profile.")

    print()
    print("Verifying PRIMAL solution against original instance:")
    ok = verify_solution(
        Gb, Gp, p_star, pi_sol, U_sol,
        print_matrices=args.print_matrices,
    )
    return 0 if ok else 2


if __name__ == "__main__":
    sys.exit(main())