#!/usr/bin/env python3
"""
Convert a BSGS-style automorphism JSON (as produced in aut_generators_*.json)
into the permutation-row format expected by the C++ AED loader:

Header: "<num_perms> <n>"
Rows:   space-separated permutation of 0..n-1, one per line

By default the identity permutation is always included, and then up to L-1
additional permutations are drawn from the generated group (breadth-first
closure of the provided strong generators).
"""
import argparse
import json
import random
from collections import deque
from typing import Iterable, List, Tuple


def compose(a: Tuple[int, ...], b: Tuple[int, ...]) -> Tuple[int, ...]:
    """Return permutation a∘b (apply b then a)."""
    return tuple(a[b[i]] for i in range(len(a)))


def generate_group(n: int, generators: List[List[int]]) -> List[Tuple[int, ...]]:
    """Enumerate the subgroup generated by the given permutations (small groups)."""
    gens = [tuple(g) for g in generators]
    identity = tuple(range(n))
    seen = {identity}
    order = [identity]
    queue: deque[Tuple[int, ...]] = deque([identity])

    while queue:
        g = queue.popleft()
        for h in gens:
            gh = compose(h, g)
            if gh not in seen:
                seen.add(gh)
                order.append(gh)
                queue.append(gh)
    return order


def select_perms(group: List[Tuple[int, ...]], L: int, seed: int | None) -> List[Tuple[int, ...]]:
    """Select up to L permutations, keeping identity first."""
    if not group:
        return []
    identity = tuple(range(len(group[0])))
    others = [p for p in group if p != identity]

    rng = random.Random(seed)
    rng.shuffle(others)

    selected = [identity]
    selected.extend(others[: max(0, L - 1)])
    return selected


def write_perms(path: str, perms: Iterable[Tuple[int, ...]], n: int) -> None:
    perms = list(perms)
    with open(path, "w", encoding="ascii") as f:
        f.write(f"{len(perms)} {n}\n")
        for p in perms:
            f.write(" ".join(str(x) for x in p))
            f.write("\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert BSGS JSON to permutation rows for AED input.")
    parser.add_argument("json_in", help="Input JSON with fields: n, sgs (list of permutations)")
    parser.add_argument("out_path", help="Output path for permutation rows")
    parser.add_argument("--L", type=int, default=16, help="Number of permutations to output (default: 16)")
    parser.add_argument("--seed", type=int, default=None, help="Optional random seed for sampling permutations")
    args = parser.parse_args()

    with open(args.json_in, "r", encoding="ascii") as f:
        data = json.load(f)

    n = int(data["n"])
    generators: List[List[int]] = data["sgs"]

    group = generate_group(n, generators)
    perms = select_perms(group, args.L, args.seed)
    write_perms(args.out_path, perms, n)
    print(f"Wrote {len(perms)} permutations (n={n}) to {args.out_path}")


if __name__ == "__main__":
    main()
