#!/usr/bin/env python3
"""
schreier_sims_eBCH.py

Load an automorphism generator set for an eBCH code (saved as JSON by
part_gen_set_eBCH.py) and run a basic Schreier–Sims algorithm to build
a base + stabilizer chain, compute the group order, and support membership tests.

Expected JSON format (from part_gen_set_eBCH.py):
{
  "n": <int>,                   # code length
  "k": <int>,                   # dimension
  "|H|": <int>,                 # number of generators (just informational)
  "H_perms": [ [..], [..], ... ],   # list of permutations, each length n
  "generator_records": [ {"type": ..., "meta": ...}, ... ]
}
"""

import json
import argparse
import numpy as np


# ================================================================
# Basic permutation operations
# ================================================================

def compose(p: np.ndarray, q: np.ndarray) -> np.ndarray:
    """
    Composition p ∘ q, acting on the right:
      (p ∘ q)(i) = p[q[i]]
    Both p, q shape: (n,)
    """
    return p[q]


def inverse(p: np.ndarray) -> np.ndarray:
    """
    Compute inverse permutation p^{-1}.
    """
    n = len(p)
    inv = np.empty(n, dtype=int)
    inv[p] = np.arange(n, dtype=int)
    return inv


def is_identity(p: np.ndarray) -> bool:
    """
    Check if p is the identity permutation.
    """
    return np.all(p == np.arange(len(p), dtype=int))


# ================================================================
# Orbit and transversal for a base point
# ================================================================

def orbit_and_transversal(gens, base_point: int, n: int):
    """
    Compute the orbit of base_point under group <gens>, and a transversal
    (Schreier tree) representing each orbit element as a group element.

    Parameters
    ----------
    gens : list[np.ndarray]
        List of permutations generating the current group G^{(i)}.
    base_point : int
        The base point b_i whose orbit we explore.
    n : int
        Degree of the permutation group (number of coordinates).

    Returns
    -------
    orbit : list[int]
        The orbit Δ_i = b_i^{G^{(i)}}.
    trans : dict[int, np.ndarray]
        A dictionary mapping each x in orbit to some t_x ∈ G^{(i)} such that
        t_x(base_point) = x.
    """
    id_perm = np.arange(n, dtype=int)

    orbit = [base_point]
    trans = {base_point: id_perm}
    queue = [base_point]

    while queue:
        x = queue.pop()
        t_x = trans[x]
        for s in gens:
            y = s[x]
            if y not in trans:
                # New orbit element; t_y = s ∘ t_x
                trans[y] = compose(s, t_x)
                orbit.append(y)
                queue.append(y)

    return orbit, trans


# ================================================================
# Schreier generators for stabilizer of base point
# ================================================================

def schreier_generators(gens_i, orbit, trans, n: int):
    """
    Produce Schreier generators for the stabilizer G^{(i+1)} of the current base point.

    Schreier lemma: if G_i acts on the orbit of b_i, then the stabilizer of b_i
    is generated by all elements of the form

        t_x * s * t_{x^s}^{-1}

    for x in orbit, s in gens_i, where t_x is any element mapping b_i -> x.

    Parameters
    ----------
    gens_i : list[np.ndarray]
        Generators of G^{(i)}.
    orbit : list[int]
        The orbit Δ_i of b_i under G^{(i)}.
    trans : dict[int, np.ndarray]
        Transversal: maps x -> t_x with t_x(b_i) = x.
    n : int
        Degree of the permutation group.

    Returns
    -------
    new_gens : list[np.ndarray]
        List of Schreier generators (not yet filtered/deduplicated).
    """
    new_gens = []
    seen = set()  # to avoid exact duplicates (by tuple representation)

    for x in orbit:
        t_x = trans[x]
        for s in gens_i:
            y = s[x]
            t_y = trans[y]
            # h = t_x ∘ s ∘ t_y^{-1}
            # h = compose(t_x, compose(s, inverse(t_y)))
            h = compose(inverse(t_y), compose(s, t_x))

            if is_identity(h):
                continue
            key = tuple(h.tolist())
            if key not in seen:
                seen.add(key)
                new_gens.append(h)

    return new_gens


# ================================================================
# Schreier–Sims chain construction (simple deterministic version)
# ================================================================

def schreier_sims(gens, base, n: int):
    """
    Build a base + stabilizer chain {G^{(i)}} using a simple Schreier–Sims procedure.

    Parameters
    ----------
    gens : list[np.ndarray]
        Initial generators of the full group G.
    base : list[int]
        Base points b_1, b_2, ..., b_k (indices in 0..n-1).
    n : int
        Degree of the permutation group.

    Returns
    -------
    chain : list[dict]
        Each level i is represented as a dictionary:
        {
          "base_point": int,
          "gens": list[np.ndarray],   # strong generators for G^{(i)} (not heavily reduced)
          "orbit": list[int],
          "trans": dict[int, np.ndarray]
        }

        The stabilizer generators for the next level are derived internally.
    """
    chain = []
    gens_i = [g.copy() for g in gens if not is_identity(g)]

    for b in base:
        if not gens_i:
            # The remaining stabilizers are trivial.
            break

        # 1) Orbit and transversal at this level
        orbit_i, trans_i = orbit_and_transversal(gens_i, b, n)

        # 2) Schreier generators that (by construction) fix b
        schreier_gens_i = schreier_generators(gens_i, orbit_i, trans_i, n)

        # 3) Explicitly filter to those that fix b (paranoia / clarity)
        stab_gens = []
        seen_stab = set()
        for h in schreier_gens_i:
            if h[b] != b:
                continue
            key = tuple(h.tolist())
            if key not in seen_stab and not is_identity(h):
                seen_stab.add(key)
                stab_gens.append(h)

        # Store this level's data
        chain.append({
            "base_point": b,
            "gens": gens_i,      # generators for G^{(i)}
            "orbit": orbit_i,
            "trans": trans_i,    # transversal for orbit of b
        })

        # Stabilizer of b becomes the next group's generating set
        gens_i = stab_gens

    return chain


# ================================================================
# Group order and membership test
# ================================================================

def group_order_from_chain(chain):
    """
    Compute the group order from the chain using |G| = Π_i |orbit_i|.

    Note:
    This is valid when the chain reaches trivial stabilizer; for typical
    small/groups we encounter (e.g., eBCH automorphism groups with your
    generator set), this is okay.
    """
    order = 1
    for level in chain:
        order *= len(level["orbit"])
    return order


def sift_membership(g: np.ndarray, chain, n: int) -> bool:
    """
    Membership test: check if g lies in the group defined by the stabilizer chain.

    Standard "sifting" procedure:

      For each level i with base point b_i:
        - Let image = g(b_i).
        - If image not in orbit Δ_i, then g ∉ G.
        - Otherwise, let t be transversal element with t(b_i) = image.
        - Replace g := t^{-1} ∘ g and proceed to the next level.

      If finally we get identity, then g ∈ G.
    """
    h = g.copy()
    for level in chain:
        b = level["base_point"]
        image = h[b]
        trans = level["trans"]
        if image not in trans:
            return False
        t = trans[image]
        h = compose(inverse(t), h)
    return is_identity(h)

def sift_remainder_left(g: np.ndarray, chain, n: int):
    """
    Left-coset sifting remainder.

    Performs the same sifting loop as sift_membership, but instead of returning
    True/False, returns the residual permutation r after removing the subgroup part
    from the LEFT using the chain transversals.

    If at some level the image is not in the orbit/transversal table, we stop and
    return the current residual r (still well-defined and deterministic).

    Property (key for left cosets):
        For any h in H, sift_remainder_left(h ∘ g) == sift_remainder_left(g).
    """
    r = g.copy()
    for level in chain:
        b = level["base_point"]
        image = int(r[b])
        trans = level["trans"]

        # If image not in orbit at this level, can't reduce further.
        if image not in trans:
            break

        t = trans[image]          # t(b)=image
        r = compose(inverse(t), r)  # r <- t^{-1} ∘ r

    return r


# def right_coset_key(g: np.ndarray, chain, n: int):
#     """
#     Canonical key for RIGHT coset gH, computed via inversion trick:
#         gH  <->  H g^{-1}.

#     Returns a hashable tuple.
#     Property (what you want):
#         right_coset_key(g ∘ h) == right_coset_key(g)  for all h in H.
#     """
#     rinv = inverse(g)
#     rem = sift_remainder_left(rinv, chain, n)
#     return tuple(int(x) for x in rem.tolist())
def sift_remainder_right(g: np.ndarray, chain, n: int):
    """
    Right-coset sifting remainder.

    Returns residual r after removing subgroup part from the RIGHT using transversals.

    Property:
        For any h in H, sift_remainder_right(g ∘ h) == sift_remainder_right(g).
    """
    r = g.copy()
    for level in chain:
        b = level["base_point"]
        image = int(r[b])
        trans = level["trans"]

        if image not in trans:
            break

        t = trans[image]                 # t(b) = image
        r = compose(r, inverse(t))       # r <- r ∘ t^{-1}

    return r


def right_coset_key(g: np.ndarray, chain, n: int):
    """
    Hashable key for right coset gH using right sifting remainder.
    """
    rem = sift_remainder_right(g, chain, n)
    return tuple(int(x) for x in rem.tolist())


# ================================================================
# I/O helpers
# ================================================================

def load_generators_from_json(path):
    """
    Load generator permutations from a JSON file produced by part_gen_set_eBCH.py.
    """
    with open(path, "r") as f:
        data = json.load(f)

    n = data["n"]
    H_perms = data["H_perms"]
    gens = [np.array(p, dtype=int) for p in H_perms]
    return n, gens, data


# ================================================================
# Main CLI
# ================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Run Schreier–Sims on an eBCH automorphism generator set JSON."
    )
    parser.add_argument(
        "json_path",
        help="Path to JSON file containing H_perms (e.g., aut_generators_eBCH_m4_t2.json)."
    )
    parser.add_argument(
        "--base",
        type=str,
        default=None,
        help="Comma-separated list of base points (e.g. '0,1,2'). "
             "If omitted, uses 0..n-1 until stabilizer becomes trivial."
    )

    args = parser.parse_args()

    # Load generator set
    n, gens, meta = load_generators_from_json(args.json_path)
    print(f"[info] Loaded generator set from {args.json_path}")
    print(f"       n = {n}, k = {meta.get('k', '?')}, |H| (raw gens) = {len(gens)}")

    # Determine base
    if args.base is not None:
        base = [int(x) for x in args.base.split(",") if x.strip() != ""]
    else:
        # naive base: [0, 1, 2, ..., n-1]
        base = list(range(n))

    print(f"[info] Using base B = {base}")

    # Run Schreier–Sims
    chain = schreier_sims(gens, base, n)

    print("\n[info] Schreier–Sims chain summary:")
    for i, level in enumerate(chain, start=1):
        b = level["base_point"]
        orbit_size = len(level["orbit"])
        num_gens = len(level["gens"])
        print(f"  Level {i}: base_point = {b}, |orbit| = {orbit_size}, |gens(G^{({i})})| ≈ {num_gens}")

    order = group_order_from_chain(chain)
    print(f"\n[info] Estimated group order |G| = {order}")

    # Small demo: test membership of each original generator
    print("\n[info] Membership test of original generators:")
    for idx, g in enumerate(gens):
        ok = sift_membership(g, chain, n)
        print(f"  gen #{idx}: in group? {ok}")
    # ============================================================
    # Save results to JSON
    # ============================================================

    # Collect full SGS from chain (union of all level generators)
    sgs = []
    sgs_seen = set()
    for level in chain:
        for g in level["gens"]:
            key = tuple(g.tolist())
            if key not in sgs_seen and not is_identity(g):
                sgs_seen.add(key)
                sgs.append(g.tolist())

    # Prepare JSON-serializable structure
    json_out = {
        "file_source": args.json_path,
        "n": n,
        "base": base,
        "group_order": int(order),
        "num_levels": len(chain),
        "levels": [],
        "sgs": sgs,
    }

    # for i, level in enumerate(chain, start=1):
    #     json_out["levels"].append({
    #         "level": i,
    #         "base_point": int(level["base_point"]),
    #         "orbit": [int(x) for x in level["orbit"]],
    #         "orbit_size": int(len(level["orbit"])),
    #         "num_gens": int(len(level["gens"])),
    #     })
    for i, level in enumerate(chain, start=1):
        # Store transversals aligned with orbit order (compact + JSON-friendly)
        orbit_list = [int(x) for x in level["orbit"]]
        trans_dict = level["trans"]  # dict[int -> np.ndarray]
        trans_list = [trans_dict[x].tolist() for x in orbit_list]

        json_out["levels"].append({
            "level": i,
            "base_point": int(level["base_point"]),
            "orbit": orbit_list,
            "orbit_size": int(len(orbit_list)),
            "num_gens": int(len(level["gens"])),
            "trans": trans_list,   # trans[j] maps base_point -> orbit[j]
        })


    # Output path
    out_path = args.json_path.replace(".json", "_schreier_sims.json")

    with open(out_path, "w") as f:
        json.dump(json_out, f, indent=2)

    print(f"\n[info] Schreier–Sims results saved → {out_path}")



if __name__ == "__main__":
    main()
